In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
dataset = pd.read_csv('BCHBTC.csv')
x = dataset.iloc[:, 2:-7].values
y = dataset.iloc[:, -7].values

In [7]:
print(x)
print(y)

[[0.028439 0.028439 0.028439]
 [0.028441 0.028462 0.028438]
 [0.028462 0.028462 0.028462]
 ...
 [0.009211 0.009212 0.009206]
 [0.009206 0.009208 0.009205]
 [0.009206 0.00921  0.009204]]
[0.028439 0.028462 0.028462 ... 0.009206 0.009205 0.009209]


In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [9]:
from sklearn.linear_model import LinearRegression
multi = LinearRegression()
multi.fit(x_train, y_train)

LinearRegression()

In [10]:
y_predict = multi.predict(x_test)
np.set_printoptions(precision = 6)
print(np.concatenate((y_predict.reshape(len(y_predict),1), y_test.reshape(len(y_test),1)),1))

[[0.014412 0.014416]
 [0.039098 0.039168]
 [0.021665 0.021666]
 ...
 [0.026516 0.026515]
 [0.025014 0.025013]
 [0.021406 0.021409]]


In [11]:
from sklearn.metrics import r2_score
r2_score(y_test, y_predict)

0.9999979312236092